Repository helldivers-2/json, pull requests merged in 2024-04, with the labels that each got.

#4 Adding Additional Mapping Files
  assignments/reward_type.json
  assignments/tasks/values.json
  assignments/types.json
  campaign_types.json
  items/armor/README.md
  items/armor/armor.json
  items/armor/passive.json
  items/armor/slot.json
  items/boosters.json
  items/item_names.json
  items/weapons/README.md
  items/weapons/fire_modes.json
  items/weapons/grenades.json
  items/weapons/primary.json
  items/weapons/secondary.json
  items/weapons/traits.json
  items/weapons/types.json
  warbonds/cutting_edge.json
  warbonds/helldivers_mobilize.json
  warbonds/steeled_veterans.json
Labels: documentation, enhancement

#6 Add Environments and Biomes, Restructure Sectors
  factions.json
  planets.json
  planets/biomes.json
  planets/environmentals.json
  planets/planets.json
  sectors.json
Labels: enhancement

#16 Update json-validate.yml
  .github/workflows/json-validate.yml
Labels: bug

#18 add warbonds.json
  warbonds.json
Labels: documentation, enhancement

#24 Fixes for FS-61 Dreadnought; Breaker Spray&Pray; Weapon Traits
  items/armor/armor.json
  items/weapons/primary.json
  items/weapons/traits.json
Labels: bug

#25 Adjust Premium Warbond Tracking
  warbonds.json
  warbonds/democratic_detonation.json
Labels: feature

#26 Implement Issue templates; Codeowners; Labeler Action
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/json-validate.yml
Labels: documentation

#28 Remove duplicate reward types file
  assignments/reward_type.json
Labels: bug

#32 Correct mappings for armor.json
  items/armor/armor.json
Labels: bug
